wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1714422828.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.18
      5: 0.16.4
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
