# Network Architecture
model:
  type: "CNN"
  num_layers: 5
  hidden_units: 256
  num_classes: 38

# Training Hyperparameters
training:
  batch_size: 5
  learning_rate: 0.001
  epochs: 1

# Data Preprocessing
#preprocessing:
image_size: [224, 224]
normalization: "standardize"
#augmentation:
horizontal_flip: true
rotation_range: 20
