name: Run Test with Pytest

on:
  # Set the workflow to run on push events
  push:
    branches:
      - main
  # Set the workflow to run on pull_request events
  pull_request:
    branches:
      - main

jobs:
  # Test job: Run unit tests and generate coverage report
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dependencies from requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          # Run unit tests with pytest and capture coverage information.
          pip install coverage pytest
          coverage run -m pytest -v -s

  # Coverage-report job: Run only if the test job completes successfully
  coverage-report:
    runs-on: ubuntu-latest
    needs: test  # Ensure the test job has completed successfully
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate Coverage Report
        run: coverage report -m
